name: wohlig devops test

on:
  push:
    branches:
      - 'uat'

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN100 }}

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: checkout test-commits
        uses: actions/checkout@v3
      - name: checkout test-gitops
        run: git clone https://Javed-Patel-wohlig:${{ secrets.TOKEN100 }}@github.com/Javed-Patel-wohlig/test-gitops.git
      - name: configure git
        run: |
          git config --global user.email "javed.patel@wohlig.com"
          git config --global user.name "Javed-Patel-wohlig"
      - name: Update count.txt
        run: |
          cd test-gitops
          if [[ ! -f count.txt ]]; then
            echo "Error: count.txt not found."
            exit 1
          fi
          count=$(grep -oP 'my commit count is : \K\d+' count.txt)
          echo "hello I'm devops" >> count.txt
          echo "my commit count is : $((count + 50))" >> count.txt
          echo "thank you" >> count.txt
          git add .
          git commit -m "update new count"
      - name: Push changes (if any)
        run: |
          cd test-gitops
          if [[ $(git status --porcelain | grep -c count.txt) -gt 0 ]]; then
            git push
          fi